### ISSUE TITLE
Сразу после установки

### ISSUE THREAD

**Issue by voischev** [tadatuta/sublime-bemmet#1]
Установил. Перезагрузил. Назначил клавишу. (она не сработала). cmd+shift+p>Expand bemmet... 

![2015-08-04 20 43 46](https://cloud.githubusercontent.com/assets/1510217/9068040/97382a82-3ae9-11e5-8f4c-4a66845e7208.png)

**Comment by tadatuta** [comment]
@voischev Ага, спасибо, это у меня `node_modules` в глобальном `gitignore` прописаны, вот я их и не закоммитил. Исправил в https://github.com/tadatuta/sublime-bemmet/commit/2dd7224824f431e735b0322ad55db83484d2b304, но оно, похоже, как-то не моментально подтягивается :(

**Comment by tadatuta** [comment]
У меня подтянулось, попробуй, пожалуйста

**Comment by voischev** [comment]
Все хорошо. Только почему то { "keys": ["alt+super+e"], "command": "bemmet" } не сработало. Другие сочетания ок.
